In [57]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [4]:
pd.read_csv("https://raw.githubusercontent.com/JuanPabloMF/datasets-platzi-course/master/datasets/peliculas.csv")

movie_title  ...        gross
0                                               Avatar   ...  760505847.0
1             Pirates of the Caribbean: At World's End   ...  309404152.0
2                                              Spectre   ...  200074175.0
3                                The Dark Knight Rises   ...  448130642.0
4     Star Wars: Episode VII - The Force Awakens    ...  ...          NaN
...                                                 ...  ...          ...
5038                           Signed Sealed Delivered   ...          NaN
5039                         The Following               ...          NaN
5040                              A Plague So Pleasant   ...          NaN
5041                                  Shanghai Calling   ...      10443.0
5042                                 My Date with Drew   ...      85222.0

[5043 rows x 19 columns]

In [6]:
a1 = np.array([1,2,3])
type(a1)

numpy.ndarray

In [0]:
a2 = np.arange(10)

In [8]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a3 = np.zeros((2,3))
a4 = np.ones((2,3))

In [15]:
from IPython.display import display
display(a3)
display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
a5 = np.linspace(0,1,11)
display(a5)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
a5.dtype

dtype('float64')

In [21]:
a3.shape

(2, 3)

In [24]:
a1D = np.array([1,2,3])
a2D = np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [25]:
np.array_equal(a1D, a2D)

False

In [30]:
new_dims = (1, a1D.shape[0])
a = a1D.reshape(new_dims)
a

array([[1, 2, 3]])

In [29]:
np.array_equal(a,a2D)

True

In [31]:
a = np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [38]:
a[2,2]

-1

In [39]:
a = np.arange(10)
b = np.eye(3)
display(a)
display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
a[:5]

array([0, 1, 2, 3, 4])

Acceder a columna de matriz

In [43]:
b[0:3,1]

array([0., 1., 0.])

Acceder a fila de matriz

In [44]:
b[2,0:3]

array([0., 0., 1.])

In [45]:
b[::]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
a =np.arange(4)
print("a     =",a)
print("a + 5 =",a+5)
print("a - 5 =",a-5)
print("a * 2 =",a*2)
print("a / 2 =",a/2)
print("a // 2 =",a//2)
print("-a     =",-a)
print("a ** 2 =",a**2)
print("a % 2 =",a % 2)

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
-a     = [ 0 -1 -2 -3]
a ** 2 = [0 1 4 9]
a % 2 = [0 1 0 1]


In [49]:
a*a

array([0, 1, 4, 9])

In [52]:
a = np.arange(4)
b = np.arange(1,5)
display(b)
display(np.exp(a))
display(np.log(b))
display(np.sqrt(a))
display(np.greater(a,b))

array([1, 2, 3, 4])

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [54]:
a = np.arange(10)
display(np.mean(a))
display(np.median(a))

4.5

4.5

In [55]:
np.percentile(a,40)

3.6

In [56]:
np.random.random(10)

array([0.72382035, 0.70510475, 0.23198111, 0.55577994, 0.47139273,
       0.03129073, 0.88674064, 0.23887087, 0.76267231, 0.35276118])