In [0]:
import numpy as np 
from sklearn.linear_model import LogisticRegression

In [0]:
x = np.array([0.5, 0.75, 1, 1.25, 1.5, 1.75, 1.75, 2, 2.25, 2.5, 2.75, 3, 3.25, 3.5, 4, 4.25, 4.5,
4.75, 5, 5.5]).reshape(-1,1)
y = ([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])

In [3]:
regresion_logictica = LogisticRegression()

regresion_logictica.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
x_nuevo = np.array([1,2,3,4,5,6]).reshape(-1,1)

In [6]:
prediccion = regresion_logictica.predict(x_nuevo)
print(prediccion)

probabilidades_prediccion = regresion_logictica.predict_proba(x_nuevo)
print(probabilidades_prediccion)
print(probabilidades_prediccion[:,1])

[0 0 1 1 1 1]
[[0.87984046 0.12015954]
 [0.69895285 0.30104715]
 [0.42402118 0.57597882]
 [0.18924992 0.81075008]
 [0.06891381 0.93108619]
 [0.02293029 0.97706971]]
[0.12015954 0.30104715 0.57597882 0.81075008 0.93108619 0.97706971]
